version: '3.9'

services:
  postgres:
    image: postgres:9.6
    restart: unless-stopped
    environment:
      POSTGRES_DB: 'webstep'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'pg123456'
    ports:
        - '5432:5432'
    volumes:
        - ../../../ro:/ro:ro
        - ../../../rw:/rw
        - ../../../Downloads:/dl:ro
        - ../.data/pg96:/var/lib/postgresql/data/
    container_name: PSQL9.6

